CREATE TABLE EMPLOYEES
(EMP_ID INT PRIMARY KEY,
EMP_NAME VARCHAR(50),
SALARY INT,
JOIN_DATE INT
);
SELECT * FROM EMPLOYEES;
DESC EMPLOYEES;
SHOW CREATE TABLE EMPLOYEES;
CREATE TABLE DEPARTMENTS(
DEPT_ID INT PRIMARY KEY,
DEPT_NAME VARCHAR(50)
);
SELECT*FROM DEPARTMENTS;
ALTER TABLE EMPLOYEES
ADD COLUMN EMAIL VARCHAR(100);
ALTER TABLE EMPLOYEES
ADD COLUMN PHONE INT NOT NULL;
ALTER TABLE DEPARTMENTS
ADD COLUMN DEPT_LOCATION VARCHAR(50);
ALTER TABLE EMPLOYEES
MODIFY EMP_NAME VARCHAR(100);
ALTER TABLE DEPARTMENTS
ADD PRIMARY KEY(DEPT_ID);
SHOW CREATE TABLE DEPARTMENTS;

ALTER TABLE EMPLOYEES 
ADD FOREIGN KEY (DEPT_ID)
REFERENCES DEPARTMENTS (DEPT_ID);

ALTER TABLE EMPLOYEES
ADD DEPT_ID INT;

ALTER TABLE EMPLOYEES
RENAME COLUMN EMP_NAME TO EMPLOYEE_NAME;

ALTER TABLE EMPLOYEES
ADD COLUMN AGE INT CHECK (AGE>25);

ALTER TABLE EMPLOYEES
ADD COLUMN SALARY INT CHECK (SALARY>10000);

ALTER TABLE EMPLOYEES
DROP COLUMN PHONE;
DESC EMPLOYEES;
DESC DEPARTMENTS;

ALTER TABLE EMPLOYEES 
RENAME TO EMPLOYEE_DETAILS;
DESC EMPLOYEE_DETAILS;

ALTER TABLE EMPLOYEES
DROP CONSTRAINT employee_details_chk_1;
SHOW CREATE TABLE EMPLOYEE_DETAILS;

DROP TABLE DEPARTMENTS;