CREATE DATABASE COLLEGE;
USE COLLEGE;
CREATE TABLE EMPLOYEES(
EMP_ID INT,
FIRST_NAME VARCHAR(10),
LAST_NAME VARCHAR(10),
EMP_AGE INT,
EMP_ZONE VARCHAR(10)
);
-- MULTIPLE ROW ISERTION 
INSERT INTO EMPLOYEES
VALUES
-- (1,"RIYA","JOSHI",20,"NORTH"),
-- (2,"TINA","JONSON",21,"SOUTH"),
-- (3,"JAY","JOSHI",30,"EAST"),
-- (4,"AMIT","SHARMA",25,"WEST"),
(4,"SRUSHTI","PATIL",22,"NORTH"),
(4,"PRACHI","KOTULE",21,"WEST");

-- UPDATE EMPLOYEES SET EMP_AGE=22 WHERE EMP_ID=
update EMPLOYEES SET EMP_ID=5 WHERE FIRST_NAME="SRUSHTI";
SELECT * FROM EMPLOYEES;

DELETE FROM EMPLOYEES WHERE EMP_ID=4;
SET SQL_SAFE_UPDATES=0;


