CREATE DATABASE COMPANY_DB;
USE COMPANY_DB;
CREATE TABLE EMPLOYEE(
EMP_ID INT NOT NULL,
FIRST_NAME VARCHAR(10),
LAST_NAME VARCHAR(10),
EMP_AGE INT);

INSERT INTO EMPLOYEE VALUES

(1,"SRUSH","KUMAR",25),
(2,"PRACHI","KUMAR",25),
(3,"ROHAN","KUMAR",25),
(4,"AYUSH","KUMAR",25),
(5,"GAURAV","KUMAR",25),
(6,"RAVI","KUMAR",25);

SELECT * FROM EMPLOYEE;
-- TABLE3--    
CREATE TABLE EMPLOYEE3(
EMP_ID INT NOT NULL,
FIRST_NAME VARCHAR(10),
LAST_NAME VARCHAR(10),
EMP_AGE INT,
CHECK (EMP_ID>20));

ALTER TABLE EMPLOYEE3 ADD COLUMN SALARY INT ,ADD CHECK(SALARY>50000);
ALTER TABLE EMPLOYEE3 ADD COLUMN SALARY INT ,ADD CHECK(SALARY>50000);
SELECT * FROM EMPLOYEE3;
INSERT INTO EMPLOYEE3 VALUES
(21,"JAY","SHAH",21,3000000),
(30,"AMAN","SHARMA",22,200000);

-- TO CHECK CONSTRAINT-- 
SHOW CREATE TABLE EMPLOYEE3;

ALTER TABLE EMPLOYEE3 DROP CHECK EMPLOYEE3_CHK_1;

SELECT * FROM EMPLOYEE3;

CREATE TABLE EMPLOYEE6(
EMP_ID INT PRIMARY KEY,
FIRST_NAME VARCHAR(10),
LAST_NAME VARCHAR(10),
EMP_AGE INT
CHECK (EMP_AGE>20));

SELECT * FROM EMPLOYEE6;

INSERT INTO EMPLOYEE6 VALUES
(1,"JAY","SHAH",21),
(2,"AMAN","SHARMA",22),
(3,"RAVI","SHAH",21),
(30,"JPHN","SHARMA",22);

CREATE TABLE EMPLOYEE7(
EMP_ID INT PRIMARY KEY,
FIRST_NAME VARCHAR(10),
LAST_NAME VARCHAR(10),
EMP_AGE INT,
SALARY INT);
SELECT * FROM EMPLOYEE7;
INSERT INTO EMPLOYEE7 VALUES
(1,"JAY","SHAH",21,20000),
(2,"AMAN","SHARMA",22,30000),
(3,"RAVI","SHAH",21,10000),
(30,"JPHN","SHARMA",22,90000);

ALTER TABLE EMPLOYEE7 ADD CONSTRAINT CHK_EMP_AGE_SALARY
CHECK(EMP_AGE>20 AND SALARY >5000);

SHOW CREATE TABLE EMPLOYEE7;

INSERT INTO EMPLOYEE7 VALUES
(5,"RIYA","SHAH",19,2000); -- ERROR-- 
 
INSERT INTO EMPLOYEE7 VALUES
(5,"RIYA","SHAH",29,20000); 
SELECT * FROM EMPLOYEE7;
