CREATE TABLE EMPLOYEE4(
EMP_ID INT PRIMARY KEY,
FIRST_NAME VARCHAR(50),
LAST_NAME VARCHAR(50),
EMP_DEPT VARCHAR(50) DEFAULT 'OPERATIONS');

SELECT*FROM EMPLOYEE4;
INSERT INTO EMPLOYEE4(EMP_ID,FIRST_NAME,LAST_NAME)
VALUES
-- (1,"A","B"),
(2,"B","B"),
(3,"C","B"),
(4,"D","B");

-- INDEXES
CREATE INDEX DEMO_INDEX ON EMPLOYEE4(FIRST_NAME);
CREATE INDEX DEMO_INDEX2 ON EMPLOYEE4(FIRST_NAME,LAST_NAME);
DROP INDEX DEMO_INDEX ON EMPLOYEE4;
SHOW INDEXES FROM EMPLOYEE4;


-- AUTO INCREMENT
CREATE TABLE PERSON
(PERSON_ID INT PRIMARY KEY AUTO_INCREMENT,
FIRST_NAME VARCHAR(50),
LAST_NAME VARCHAR(50),
AGE INT);
SELECT* FROM PERSON;

INSERT INTO PERSON(FIRST_NAME,LAST_NAME,AGE)
VALUES
-- ("SRUSHTI","GHULE",21),
-- ("PRACHI","KOTULE",20),
("GARATTE","GRAHAM",21),
("DEAN","MAVERIC",20),
("LOGAN","MAD",21),
("HANNA","WALESY",20);