CREATE TABLE STAFF(
STAFF_ID INT,
FIRST_NAME VARCHAR(50),
LAST_NAME VARCHAR(50),
DOB INT,
DEPT_ID INT
);
SELECT * FROM STAFF;
desc STAFF;
CREATE TABLE DEPARTMENT (
DEPT_ID INT,
DEPT_NAME VARCHAR(50),
DEPT_LOCATION VARCHAR(50)
);
SELECT * FROM DEPARTMENT;

ALTER TABLE STAFF ADD (LOCATION INT, JOINING_YEAR INT);
ALTER TABLE STAFF ADD (AGE INT, CONTACT_NUMBER INT);
-- MODIFY TABLE--
ALTER TABLE STAFF MODIFY LOCATION VARCHAR(50);
ALTER TABLE STAFF MODIFY FIRST_NAME TEXT;

ALTER TABLE STAFF DROP COLUMN CONTACT_NUMBER;

ALTER TABLE STAFF MODIFY LOCATION VARCHAR(30);

ALTER TABLE STAFF ADD PRIMARY KEY (STAFF_ID);
ALTER TABLE DEPARTMENT ADD PRIMARY KEY (DEPT_ID);
DESC DEPARTMENT;

ALTER TABLE STAFF DROP primary key;
-- ALTER TABLE STAFF DROP FOREIGN KEY DEPT_ID --
-- ADD FORIGEN KEY TO STAFF--

ALTER TABLE STAFF ADD FOREIGN KEY(DEPT_ID) REFERENCES DEPARTMENT(DEPT_ID);

DESC STAFF;